### PR TITLE
fix: available capacity calculation

### LINKED ISSUE #168: Capacity endpoint should account for capacity buffer
In the capacity engine we should account for the capacity buffer when calculating maximum available capacity.

### LINKED ISSUE #169: calculateOptimalPoolAllocation tests rewrite
Tests for calculateOptimalPoolAllocation should be rewritten as the code and function arguments changed in the meantime (pools now sorted by priority).

### LINKED ISSUE #170: quoteEngine pool order on return
quote should return pools in the same priority order as allocation is calculated.

by @rackstar https://github.com/NexusMutual/cover-router/pull/164#discussion_r1961507757

> how we displayed the ordering of the pools get jumbled because we do Object.keys(allocations).
its best if calculatePoolAllocations returns an array instead of an object, since all we do on the allocation object is iterate over it anyway and an array would preserve the ordering.
then we can add a test to ensure that the resulting array of quoteEngine actually has the pools in the order that we expect.

### PR DESCRIPTION
**Pull request by duxxud**
## Description

Closes #168, Closes #169, Closes #170

- Moving calculation of available capacity to one place (in helpers) to be used by both `capacityEngine` and `quoteEngine`.
- `calculatePoolAllocation` is refactored to return an array instead of object, and `quoteEngine` now returns pools in the same priority order as allocation is taken. 

## Testing

Fixed unit tests, and rewrote calculatePoolAllocation tests.

## Checklist

- [x] Performed a self-review of my own code
- [ ] Made corresponding changes to the documentation

### CODE REVIEW

File: src/lib/quoteEngine.js [hunk 1]
```diff
@@ -62,7 +51,7 @@ const calculatePoolAllocations = (coverAmount, pools) => {
 
   if (coverAmountLeft > 0) {
```
Comment (rackstar) [inline src/lib/quoteEngine.js:52]: coverAmountLeft is BigNumber so should be:

`if (coverAmountLeft.gt(0)) {`

Comment (rackstar) [reply src/lib/quoteEngine.js:52]: @duxxud in vscode go to settings then search and enable `checkjs`. It will use the JSDoc types to warn you if there is any type mismatch

File: src/lib/helpers.js [hunk 2]
```diff
@@ -67,7 +70,15 @@ const calculateFirstUsableTrancheIndex = (now, gracePeriod, period) => {
...
-function calculateAvailableCapacity(trancheCapacities, allocations, firstUsableTrancheIndex) {
+const bufferedCapacity = capacityInNxm => {
+  const capacityBuffer = bnMax(
+    capacityInNxm.mul(CAPACITY_BUFFER_RATIO).div(CAPACITY_BUFFER_DENOMINATOR),
+    CAPACITY_BUFFER_MINIMUM,
+  );
+  return bnMax(capacityInNxm.sub(capacityBuffer), Zero);
+};
+
+function calculateAvailableCapacityInNXM(trancheCapacities, allocations, firstUsableTrancheIndex) {
```
Comment (rackstar) [inline src/lib/helpers.js:81]: (docs) might be useful to add function annotation that this returns buffered capacity

File: src/lib/quoteEngine.js (hunk 1 above)
Comment (duxxud) [reply src/lib/quoteEngine.js]: Good catch, fixed! It was there for a long time before, and was fine only because it's comparing to 0.

> in vscode go to settings then search and enable checks

A lot of red and non important warnings if I turn it on, so needed to disable again.

File: src/lib/helpers.js (hunk 2 above)
Comment (duxxud) [reply src/lib/helpers.js:91]: added

File: src/lib/quoteEngine.js (hunk 1 above)
Comment (rackstar) [reply src/lib/quoteEngine.js]: we should refacto cover-router to TS at some point

**Review by rackstar — DISMISSED** [review]
good job. i like that we got rid of a lot of duplicate code 👍

**Review by shark0der — APPROVED** [review]

**Review by MilGard91 — APPROVED** [review]
